# See config.example.yml for documentation.
object_base: orig/GKYE01
object: sys/main.dol
hash: 977533bb96e6a16e127946396489be1b4164ac42
symbols: config/GKYE01/symbols.txt
splits: config/GKYE01/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 10
extract:
- symbol: kar_dbscreenshot_save_icon_rgb5a3
  binary: kar/db/dbscreenshot_icon_rgb5a3.bin
  header_type: none
- symbol: kar_debugconsole_font_i4_8x14
  binary: kar/debug/debugconsole_font_i4_8x14.bin
  header_type: none
- symbol: kar_sislib_romfont_glyphs_i4_32x32
  binary: kar/hsd/base/sislib_romfont_glyphs_i4_32x32.bin
  header_type: none
- symbol: kar_upnp_rootdesc_xml_8049ae10
  binary: kar/lb/lbnet/upnp_rootdesc.xml
  header_type: none
- symbol: kar_debug_romfont_end_gcpmemcard_strings_80531e40
  binary: kar/hsd/base/kar_debug_romfont_end_gcpmemcard_strings_80531e40.bin
  header_type: none
- symbol: lbl_80531E60
  binary: kar/hsd/base/lbl_80531E60.bin
  header_type: none
- symbol: lbl_80531EB0
  binary: kar/hsd/base/lbl_80531EB0.bin
  header_type: none
- symbol: lbl_805320C4
  binary: kar/hsd/base/lbl_805320C4.bin
  header_type: none
- symbol: lbl_8053210C
  binary: kar/hsd/base/lbl_8053210C.bin
  header_type: none
- symbol: lbl_80532140
  binary: kar/hsd/base/lbl_80532140.bin
  header_type: none
- symbol: lbl_8053216C
  binary: kar/hsd/base/lbl_8053216C.bin
  header_type: none
