using System.Collections.Generic;
using static KARToolkit.Core.KarDataDefinitionFactory;

namespace KARToolkit.Core
{
    internal static class KarMapDataDefinitions
    {
        public static IReadOnlyList<KarDataDefinition> All { get; } = new[]
        {
            DefineSized(
                "kar.stage.table",
                "Stage Table",
                "Maps",
                "KAR_stData",
                0x04,
                "Top-level stage table. Entries resolve map ids, music ids, spawn tables, and gameplay feature toggles.",
                "HSDRaw/AirRide/KAR_stData.cs",
                Field("stageKinds", 0x00, "HSDArrayAccessor<KAR_stKind>", "Array of stage kind records.", true, "kar.stage.kind")),
            DefineSized(
                "kar.stage.kind",
                "Stage Kind Entry",
                "Maps",
                "KAR_stKind",
                0x58,
                "One stage descriptor inside Stage.dat.",
                "HSDRaw/AirRide/KAR_stData.cs",
                Field("groundId", 0x00, "s32", "Map/ground id."),
                Field("bgmId", 0x04, "s32", "Primary BGM id."),
                Field("uraBgmId", 0x08, "s32", "Alternate BGM id."),
                Field("bgmChance", 0x0C, "s32", "Chance or selector for alternate BGM."),
                Field("defaultBgmId", 0x10, "s32", "Default BGM id."),
                Field("renderCam", 0x14, "s32", "Render camera id."),
                Field("maxPlayers", 0x18, "s32", "Maximum player count."),
                Field("startId", 0x1C, "s32", "Start position table id."),
                Field("enemyId", 0x20, "s32", "Enemy table id."),
                Field("itemId", 0x24, "s32", "Item table id."),
                Field("itemAreaId", 0x28, "s32", "Item area table id."),
                Field("vehicleId", 0x2C, "s32", "Vehicle table id."),
                Field("x30", 0x30, "s32", "Unknown stage table value."),
                Field("x34", 0x34, "s32", "Unknown stage table value."),
                Field("hasItem", 0x38, "s32", "Item enable flag."),
                Field("hasYakumono", 0x3C, "s32", "Yakumono/object enable flag."),
                Field("unknownArray", 0x40, "HSDShortArray", "Unknown short array.", true),
                Field("x44", 0x44, "s32", "Unknown stage table value."),
                Field("x48", 0x48, "s32", "Unknown stage table value."),
                Field("x4C", 0x4C, "s32", "Unknown stage table value."),
                Field("x50", 0x50, "s32", "Unknown stage table value."),
                Field("x54", 0x54, "s32", "Unknown stage table value.")),
            DefineSized(
                "kar.gr.data",
                "Map Gameplay Data",
                "Maps",
                "KAR_grData",
                0x54,
                "Top-level map gameplay data root used by Gr*.dat archives.",
                "HSDRaw/AirRide/Gr/Data/KAR_grData.cs",
                Field("unknown1", 0x00, "s32", "Unknown map header value."),
                Field("stageNode", 0x04, "KAR_grStageNode", "Stage setup node.", true),
                Field("stageParam", 0x08, "HSDAccessor", "Map-specific stage parameter block.", true),
                Field("lightNode", 0x14, "KAR_grLightGroup", "Lighting setup.", true),
                Field("collisionNode", 0x18, "KAR_grCollisionNode", "Collision geometry and collision metadata.", true),
                Field("splineNode", 0x1C, "KAR_grSplineNode", "Spline/path setup.", true),
                Field("positionNode", 0x20, "KAR_grPositionNode", "Spawn/death/item/vehicle position tables.", true, "kar.gr.positionNode"),
                Field("subAnimNode", 0x24, "KAR_grSubAnimNode", "Map sub-animation table.", true),
                Field("enemyNode", 0x28, "HSDAccessor", "Enemy placement data.", true),
                Field("itemNode", 0x2C, "HSDArrayAccessor<KAR_grItemNode>", "Item timing and spawn data.", true, "kar.gr.itemNode"),
                Field("fogNode", 0x34, "KAR_grFogNode", "Fog setup.", true),
                Field("railCollNode", 0x38, "KAR_grRailCollNode", "Rail collision data.", true),
                Field("fgmNode", 0x3C, "KAR_grFGMNode", "Map sound effect data.", true),
                Field("yakumonoNode", 0x40, "KAR_YakumonoNode", "Interactive map object data.", true),
                Field("replayNode", 0x44, "HSDAccessor", "Replay data.", true),
                Field("partitionNode", 0x48, "KAR_grCollisionTreeNode", "Collision partition tree.", true),
                Field("respawnNode", 0x4C, "KAR_grRespawnNode", "Respawn/dead-position lookup.", true),
                Field("stadiumNode", 0x50, "HSDAccessor", "Stadium-specific data.", true)),
            DefineSized(
                "kar.gr.positionNode",
                "Map Position Node",
                "Maps",
                "KAR_grPositionNode",
                0x38,
                "Map position table root for starts, enemies, gravity, airflow, conveyors, items, events, vehicles, death positions, and object positions.",
                "HSDRaw/AirRide/Gr/Data/KAR_grPositionNode.cs",
                Field("positionJoint", 0x00, "HSD_JOBJ", "Joint hierarchy used by position entries.", true),
                Field("startPositions", 0x04, "HSDArrayAccessor<KAR_grPositionList>", "Player start position lists.", true, "kar.gr.positionList"),
                Field("enemyPositions", 0x08, "HSDArrayAccessor<KAR_grPositionList>", "Enemy position lists.", true, "kar.gr.positionList"),
                Field("gravityPositions", 0x0C, "HSDArrayAccessor<KAR_grPositionList>", "Gravity position lists.", true, "kar.gr.positionList"),
                Field("airflowPositions", 0x10, "HSDArrayAccessor<KAR_grPositionList>", "Airflow position lists.", true, "kar.gr.positionList"),
                Field("conveyorPositions", 0x14, "HSDArrayAccessor<KAR_grPositionList>", "Conveyor position lists.", true, "kar.gr.positionList"),
                Field("itemPositions", 0x18, "HSDArrayAccessor<KAR_grPositionList>", "Item position lists.", true, "kar.gr.positionList"),
                Field("eventPositions", 0x1C, "HSDArrayAccessor<KAR_grPositionList>", "Event/script position lists.", true, "kar.gr.positionList"),
                Field("vehiclePositions", 0x20, "HSDArrayAccessor<KAR_grPositionList>", "Vehicle position lists.", true, "kar.gr.positionList"),
                Field("globalDeadPositions", 0x24, "HSDArrayAccessor<KAR_grPositionList>", "Global dead-position lists.", true, "kar.gr.positionList"),
                Field("localDeadPositions", 0x28, "HSDArrayAccessor<KAR_grPositionList>", "Local dead-position lists.", true, "kar.gr.positionList"),
                Field("yakumonoPositions", 0x2C, "HSDArrayAccessor<KAR_grPositionList>", "Interactive object position lists.", true, "kar.gr.positionList"),
                Field("itemAreaPositions", 0x30, "HSDArrayAccessor<KAR_grAreaPositionList>", "Item area position lists.", true, "kar.gr.areaPositionList"),
                Field("vehicleAreaPositions", 0x34, "HSDArrayAccessor<KAR_grAreaPositionList>", "Vehicle area position lists.", true, "kar.gr.areaPositionList")),
            DefineSized(
                "kar.gr.positionList",
                "Map Position List",
                "Maps",
                "KAR_grPositionList",
                0x0C,
                "A position-list row with joint indices, coordinate rows, and count.",
                "HSDRaw/AirRide/Gr/Data/KAR_grPositionList.cs",
                Field("jointIndices", 0x00, "HSDIntArray", "Joint index table for this position list.", true),
                Field("positionData", 0x04, "HSDArrayAccessor<KAR_grPositionData>", "Coordinate rows for this position list.", true, "kar.gr.positionData"),
                Field("count", 0x08, "s32", "Number of coordinate rows.")),
            DefineSized(
                "kar.gr.positionData",
                "Map Position Data",
                "Maps",
                "KAR_grPositionData",
                0x24,
                "Position coordinate row with position, forward vector, and up vector.",
                "HSDRaw/AirRide/Gr/Data/KAR_grPositionList.cs",
                Field("x", 0x00, "f32", "Position X."),
                Field("y", 0x04, "f32", "Position Y."),
                Field("z", 0x08, "f32", "Position Z."),
                Field("forwardX", 0x0C, "f32", "Forward vector X."),
                Field("forwardY", 0x10, "f32", "Forward vector Y."),
                Field("forwardZ", 0x14, "f32", "Forward vector Z."),
                Field("upX", 0x18, "f32", "Up vector X."),
                Field("upY", 0x1C, "f32", "Up vector Y."),
                Field("upZ", 0x20, "f32", "Up vector Z.")),
            DefineSized(
                "kar.gr.areaPositionList",
                "Map Area Position List",
                "Maps",
                "KAR_grAreaPositionList",
                0x0C,
                "Area position-list row with joint indices, area coordinate rows, and count.",
                "HSDRaw/AirRide/Gr/Data/KAR_grAreaPositionList.cs",
                Field("jointIndices", 0x00, "HSDIntArray", "Joint index table for this area position list.", true),
                Field("areaPositionData", 0x04, "HSDArrayAccessor<KAR_grAreaPositionData>", "Area coordinate rows.", true, "kar.gr.areaPositionData"),
                Field("count", 0x08, "s32", "Number of area coordinate rows.")),
            DefineSized(
                "kar.gr.areaPositionData",
                "Map Area Position Data",
                "Maps",
                "KAR_grAreaPositionData",
                0x18,
                "Area position coordinate row with origin and dimensions.",
                "HSDRaw/AirRide/Gr/Data/KAR_grAreaPositionList.cs",
                Field("x", 0x00, "f32", "Area origin X."),
                Field("y", 0x04, "f32", "Area origin Y."),
                Field("z", 0x08, "f32", "Area origin Z."),
                Field("deltaX", 0x0C, "f32", "Area delta X."),
                Field("deltaY", 0x10, "f32", "Area delta Y."),
                Field("deltaZ", 0x14, "f32", "Area delta Z.")),
            DefineSized(
                "kar.gr.itemNode",
                "Map Item Node",
                "Maps",
                "KAR_grItemNode",
                0x14,
                "Map item timing and spawn table selector row.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNode.cs",
                Field("x00", 0x00, "s32", "Unknown item node value."),
                Field("timingTable", 0x04, "KAR_grItemNodeTimingTable", "Item timing and position lookup tables.", true, "kar.gr.itemTimingTable"),
                Field("cityTrial", 0x08, "KAR_grItemNodeCityTrial", "City Trial item spawn tables.", true, "kar.gr.itemCityTrial"),
                Field("airRide", 0x0C, "KAR_grItemGeneralSpawnTable", "Air Ride item spawn table.", true, "kar.gr.itemGeneralSpawnTable"),
                Field("coliseum", 0x10, "KAR_grItemGeneralSpawnTable", "Coliseum item spawn table.", true, "kar.gr.itemGeneralSpawnTable")),
            DefineSized(
                "kar.gr.itemTimingTable",
                "Map Item Timing Table",
                "Maps",
                "KAR_grItemNodeTimingTable",
                0x1C,
                "Item spawn timing rows and position/area lookup tables.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeTimingTable.cs",
                Field("x00", 0x00, "s32", "Unknown timing table value."),
                Field("timingTable", 0x04, "HSDArrayAccessor<KAR_grItemNodeTimingEntry>", "Match-progress timing rows.", true, "kar.gr.itemTimingEntry"),
                Field("timingTableCount", 0x08, "s32", "Number of timing rows."),
                Field("positionTable", 0x0C, "HSDArrayAccessor<KAR_grItemNodeTimingPositionLookup>", "Item position lookup rows.", true, "kar.gr.itemTimingPositionLookup"),
                Field("positionCount", 0x10, "s32", "Number of position lookup rows."),
                Field("areaTable", 0x14, "HSDArrayAccessor<KAR_grItemNodeTimingPositionLookup>", "Item area lookup rows.", true, "kar.gr.itemTimingPositionLookup"),
                Field("areaCount", 0x18, "s32", "Number of area lookup rows.")),
            DefineSized(
                "kar.gr.itemTimingEntry",
                "Map Item Timing Entry",
                "Maps",
                "KAR_grItemNodeTimingEntry",
                0x10,
                "Item spawn timing row keyed by match progress.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeTimingTable.cs",
                Field("timing", 0x00, "f32", "Match progression timing, usually 0.0 to 1.1."),
                Field("maxItemCount", 0x04, "s32", "Maximum number of spawned items allowed."),
                Field("intervalMin", 0x08, "s32", "Minimum wait before spawning a new item."),
                Field("intervalMax", 0x0C, "s32", "Maximum wait before spawning a new item.")),
            DefineSized(
                "kar.gr.itemTimingPositionLookup",
                "Map Item Position Lookup",
                "Maps",
                "KAR_grItemNodeTimingPositionLookup",
                0x10,
                "Weighted item position or area lookup row.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeTimingTable.cs",
                Field("index", 0x00, "s32", "Index into the corresponding position or area table."),
                Field("selectionFlags", 0x04, "u8", "Selection flags."),
                Field("spawnFlags", 0x08, "s32", "Spawn flags."),
                Field("chance", 0x0C, "s32", "Weighted chance that this location is selected.")),
            DefineSized(
                "kar.gr.itemCityTrial",
                "City Trial Item Spawn Tables",
                "Maps",
                "KAR_grItemNodeCityTrial",
                0x28,
                "City Trial item, box, legendary part, and special timing spawn tables.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeCityTrial.cs",
                Field("boxSpawnTable", 0x00, "KAR_grItemNodeCityTrialBoxSpawnTable", "Box spawn chance table.", true, "kar.gr.itemCityTrialBoxSpawnTable"),
                Field("itemSpawnChanceTable", 0x04, "HSDArrayAccessor<KAR_grItemNodeCityTrialCommonSpawnTable>", "Common item spawn chance rows.", true, "kar.gr.itemCityTrialCommonSpawnTable"),
                Field("itemSpawnChanceTableCount", 0x08, "s32", "Number of common item spawn chance rows."),
                Field("legendarySpawnChanceTable", 0x0C, "HSDArrayAccessor<KAR_grItemNodeCityTrialLegendarySpawnTable>", "Legendary machine part spawn chance rows.", true, "kar.gr.itemCityTrialLegendarySpawnTable"),
                Field("x10", 0x10, "HSDAccessor", "Unknown City Trial item table pointer.", true),
                Field("x10Count", 0x14, "s32", "Unknown City Trial item table count."),
                Field("unknownTable", 0x18, "HSDArrayAccessor<KAR_grItemNodeCityTrialUnknownTable>", "Unknown City Trial item chance rows.", true, "kar.gr.itemCityTrialUnknownTable"),
                Field("unknownCount", 0x1C, "s32", "Number of unknown City Trial item chance rows."),
                Field("specialTimingTable", 0x20, "HSDArrayAccessor<KAR_grItemNodeCityTrialSpecialTiming>", "Special event timing rows.", true, "kar.gr.itemCityTrialSpecialTiming"),
                Field("specialTimingCount", 0x24, "s32", "Number of special event timing rows.")),
            DefineSized(
                "kar.gr.itemCityTrialBoxSpawnTable",
                "City Trial Box Spawn Table",
                "Maps",
                "KAR_grItemNodeCityTrialBoxSpawnTable",
                0x28,
                "City Trial colored box size spawn chances and rhythm bytes.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeCityTrial.cs",
                Field("blueSmallChance", 0x00, "u8", "Blue small box chance."),
                Field("blueMediumChance", 0x01, "u8", "Blue medium box chance."),
                Field("blueLargeChance", 0x02, "u8", "Blue large box chance."),
                Field("greenSmallChance", 0x03, "u8", "Green small box chance."),
                Field("greenMediumChance", 0x04, "u8", "Green medium box chance."),
                Field("greenLargeChance", 0x05, "u8", "Green large box chance."),
                Field("redSmallChance", 0x06, "u8", "Red small box chance."),
                Field("redMediumChance", 0x07, "u8", "Red medium box chance."),
                Field("redLargeChance", 0x08, "u8", "Red large box chance.")),
            DefineSized(
                "kar.gr.itemCityTrialCommonSpawnTable",
                "City Trial Common Item Spawn Entry",
                "Maps",
                "KAR_grItemNodeCityTrialCommonSpawnTable",
                0x18,
                "City Trial common item spawn chance row.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeCityTrial.cs",
                Field("itemId", 0x00, "s32", "Item id."),
                Field("chanceType0", 0x04, "s16", "Spawn chance type 0."),
                Field("chanceType1", 0x06, "s16", "Spawn chance type 1."),
                Field("chanceType2", 0x08, "s16", "Spawn chance type 2."),
                Field("chanceType3", 0x0A, "s16", "Spawn chance type 3."),
                Field("chanceType4", 0x0C, "s16", "Spawn chance type 4."),
                Field("chanceType5", 0x0E, "s16", "Spawn chance type 5."),
                Field("chanceType6", 0x10, "s16", "Spawn chance type 6."),
                Field("chanceType7", 0x12, "s16", "Spawn chance type 7."),
                Field("boxSpawnChance1", 0x14, "s16", "Box spawn chance 1."),
                Field("boxSpawnChance2", 0x16, "s16", "Box spawn chance 2.")),
            DefineSized(
                "kar.gr.itemCityTrialLegendarySpawnTable",
                "City Trial Legendary Spawn Entry",
                "Maps",
                "KAR_grItemNodeCityTrialLegendarySpawnTable",
                0x0E,
                "Hydra and Dragoon part appearance timing row.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeCityTrial.cs",
                Field("hydraChanceToAppear", 0x00, "u8", "Hydra chance to appear."),
                Field("hydraPiece1TimingMin", 0x01, "u8", "Hydra piece 1 minimum timing."),
                Field("hydraPiece1TimingMax", 0x02, "u8", "Hydra piece 1 maximum timing."),
                Field("hydraPiece2TimingMin", 0x03, "u8", "Hydra piece 2 minimum timing."),
                Field("hydraPiece2TimingMax", 0x04, "u8", "Hydra piece 2 maximum timing."),
                Field("hydraPiece3TimingMin", 0x05, "u8", "Hydra piece 3 minimum timing."),
                Field("hydraPiece3TimingMax", 0x06, "u8", "Hydra piece 3 maximum timing."),
                Field("dragoonChanceToAppear", 0x07, "u8", "Dragoon chance to appear."),
                Field("dragoonPiece1TimingMin", 0x08, "u8", "Dragoon piece 1 minimum timing."),
                Field("dragoonPiece1TimingMax", 0x09, "u8", "Dragoon piece 1 maximum timing."),
                Field("dragoonPiece2TimingMin", 0x0A, "u8", "Dragoon piece 2 minimum timing."),
                Field("dragoonPiece2TimingMax", 0x0B, "u8", "Dragoon piece 2 maximum timing."),
                Field("dragoonPiece3TimingMin", 0x0C, "u8", "Dragoon piece 3 minimum timing."),
                Field("dragoonPiece3TimingMax", 0x0D, "u8", "Dragoon piece 3 maximum timing.")),
            DefineSized(
                "kar.gr.itemCityTrialUnknownTable",
                "City Trial Unknown Item Chance Entry",
                "Maps",
                "KAR_grItemNodeCityTrialUnknownTable",
                0x10,
                "Unknown City Trial item chance row.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeCityTrial.cs",
                Field("itemId", 0x00, "s32", "Item id."),
                Field("chanceType0", 0x04, "s16", "Spawn chance type 0."),
                Field("chanceType1", 0x06, "s16", "Spawn chance type 1."),
                Field("chanceType2", 0x08, "s16", "Spawn chance type 2."),
                Field("chanceType3", 0x0A, "s16", "Spawn chance type 3."),
                Field("chanceType4", 0x0C, "s16", "Spawn chance type 4."),
                Field("chanceType5", 0x0E, "s16", "Spawn chance type 5.")),
            DefineSized(
                "kar.gr.itemCityTrialSpecialTiming",
                "City Trial Special Timing Entry",
                "Maps",
                "KAR_grItemNodeCityTrialSpecialTiming",
                0x14,
                "Special event item timing row.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemNodeCityTrial.cs",
                Field("eventId", 0x00, "u8", "Special event id."),
                Field("maxItemCount", 0x08, "s32", "Maximum number of spawned items allowed."),
                Field("intervalMin", 0x0C, "s32", "Minimum wait before spawning a new item."),
                Field("intervalMax", 0x10, "s32", "Maximum wait before spawning a new item.")),
            DefineSized(
                "kar.gr.itemGeneralSpawnTable",
                "Map General Item Spawn Table",
                "Maps",
                "KAR_grItemGeneralSpawnTable",
                0x0C,
                "General item spawn table used by Air Ride and Coliseum map item data.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemGeneralSpawnTable.cs",
                Field("x00", 0x00, "HSDIntArray", "Unknown integer table.", true),
                Field("items", 0x04, "HSDArrayAccessor<KAR_grItemGeneralSpawnItem>", "General item spawn rows.", true, "kar.gr.itemGeneralSpawnItem"),
                Field("count", 0x08, "s32", "Number of general item spawn rows.")),
            DefineSized(
                "kar.gr.itemGeneralSpawnItem",
                "Map General Item Spawn Entry",
                "Maps",
                "KAR_grItemGeneralSpawnItem",
                0x10,
                "General item spawn chance row.",
                "HSDRaw/AirRide/Gr/Data/KAR_grItemGeneralSpawnTable.cs",
                Field("itemId", 0x00, "s32", "Item id."),
                Field("chance1", 0x04, "s32", "Spawn chance 1."),
                Field("chance2", 0x08, "s32", "Spawn chance 2."),
                Field("chance3", 0x0C, "s32", "Spawn chance 3.")),
            Define(
                "kar.gr.eventDataAll",
                "Map Event/Script Data",
                "Maps",
                null,
                "Top-level event/script root tied to a map bundle. The decomp names these roots grEventDataAll*.",
                "Map event archives and grEventDataAll* root naming",
                Field("eventScripts", null, "unknown", "Map event and script payloads. Exact structure still needs decomp/Ghidra backing.")),
        };
    }
}
