using System.Collections.Generic;
using System.Linq;

namespace KARToolkit.Core
{
    internal static class KarProjectToolkitWorkflowCatalog
    {
        public static IReadOnlyList<KarProjectToolkitWorkflow> CreateBuiltIn(
            KarProjectToolkitWorkflowProviderContext providerContext)
        {
            KarProjectToolkitSnapshot snapshot = providerContext.Snapshot;
            KarProjectResourceGraph graph = providerContext.Graph;
            IReadOnlyList<KarProjectDomainContext> domains = providerContext.Domains;
            int dataFieldCount = providerContext.DataFieldCount;
            int editableDataFieldCount = providerContext.EditableDataFieldCount;
            int importResourceCount = providerContext.ImportResourceCount;
            int readableResourceCount = providerContext.ReadableResourceCount;
            int exportableResourceCount = providerContext.ExportableResourceCount;
            int a2dEntryCount = providerContext.A2DEntryCount;

            List<KarProjectToolkitWorkflow> workflows = new List<KarProjectToolkitWorkflow>
            {
                Workflow(
                    "project-summary",
                    "project",
                    "Project Summary",
                    "Open the extracted project and report source/output roots and file counts.",
                    "project",
                    "<source-folder>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: false,
                    targetCount: 1),
                Workflow(
                    "toolkit-snapshot",
                    "project",
                    "Toolkit Snapshot",
                    "Create a project-level snapshot of domains, contexts, outputs, and inspection issues.",
                    "toolkit",
                    "<source-folder>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: false,
                    targetCount: 1,
                    outputCount: snapshot.OutputFileCount + snapshot.ResourceByteOutputCount + snapshot.A2DEntryOutputCount,
                    modifiedOutputCount: snapshot.ModifiedProjectOutputFileCount + snapshot.ModifiedResourceByteOutputCount + snapshot.ModifiedA2DEntryOutputCount,
                    inspectionIssueCount: snapshot.DomainInspectionIssueCount),
                Workflow(
                    "toolkit-domains",
                    "project",
                    "Toolkit Domains",
                    "List the high-level project domains exposed by the toolkit surface.",
                    "domains",
                    "<source-folder>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: false,
                    targetCount: domains.Count,
                    inspectionIssueCount: snapshot.DomainInspectionIssueCount),
                Workflow(
                    "validate-project",
                    "project",
                    "Validate Project",
                    "Run project and schema validation against the extracted source folder.",
                    "validate",
                    "<source-folder>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: false,
                    targetCount: snapshot.FileCount,
                    inspectionIssueCount: snapshot.DomainInspectionIssueCount),

                Workflow(
                    "list-files",
                    "files",
                    "List Files",
                    "List extracted files with KAR kind/category metadata and output-copy state.",
                    "files",
                    "<source-folder>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: snapshot.FileCount,
                    outputCount: snapshot.OutputFileCount,
                    modifiedOutputCount: snapshot.ModifiedProjectOutputFileCount),
                Workflow(
                    "archive-contexts",
                    "files",
                    "Archive Contexts",
                    "Inspect HSD archive roots, schemas, field coverage, and output state.",
                    "archive-contexts",
                    "<source-folder> [relative-path]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: graph.FileCount,
                    outputCount: snapshot.OutputFileCount,
                    modifiedOutputCount: snapshot.ModifiedProjectOutputFileCount,
                    inspectionIssueCount: snapshot.DomainInspectionIssueCount),
                Workflow(
                    "copy-file-output",
                    "files",
                    "Copy File To Output",
                    "Stage a source file under the configured output folder.",
                    "copy",
                    "<source-folder> <relative-path>",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: false,
                    targetCount: snapshot.FileCount,
                    outputCount: snapshot.OutputFileCount,
                    modifiedOutputCount: snapshot.ModifiedProjectOutputFileCount),

                Workflow(
                    "list-resources",
                    "resources",
                    "List Resources",
                    "List addressable file, HSD root, and A2D entry resources.",
                    "resources",
                    "<source-folder> [resource-address]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: graph.ResourceCount,
                    outputCount: snapshot.ResourceOutputCount,
                    modifiedOutputCount: snapshot.ModifiedResourceOutputCount),
                Workflow(
                    "resource-contexts",
                    "resources",
                    "Resource Contexts",
                    "Combine resource details, output status, byte status, fields, relationships, and script metadata.",
                    "resource-contexts",
                    "<source-folder> [resource-address]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: graph.ResourceCount,
                    outputCount: snapshot.ResourceOutputCount + snapshot.ResourceByteOutputCount,
                    modifiedOutputCount: snapshot.ModifiedResourceOutputCount + snapshot.ModifiedResourceByteOutputCount),
                Workflow(
                    "resource-action-plans",
                    "resources",
                    "Resource Action Plans",
                    "Preview resource action readiness and output-write targets without writing files.",
                    "resource-action-plans",
                    "<source-folder> [resource-address]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: graph.ResourceCount,
                    outputCount: snapshot.ResourceOutputCount + snapshot.ResourceByteOutputCount,
                    modifiedOutputCount: snapshot.ModifiedResourceOutputCount + snapshot.ModifiedResourceByteOutputCount),
                Workflow(
                    "resource-data",
                    "resources",
                    "Resource Data Views",
                    "Expose render-ready labeled field trees for known HSD root data.",
                    "resource-data",
                    "<source-folder> [resource-address]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: graph.HsdRootCount),
                Workflow(
                    "resource-data-fields",
                    "resources",
                    "Resource Data Fields",
                    "List flattened labeled fields with scalar edit metadata for known HSD roots.",
                    "resource-data-fields",
                    "<source-folder> [resource-address] [field-path-or-name]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: dataFieldCount),
                Workflow(
                    "edit-resource-data-field",
                    "resources",
                    "Edit Resource Data Field",
                    "Edit an editable scalar data field by resource address and field path into the output folder.",
                    "resource-data-edit",
                    "<source-folder> <archive:root> <field-path-or-name> <value>",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: false,
                    requiresValue: true,
                    targetCount: editableDataFieldCount,
                    outputCount: snapshot.ResourceOutputCount,
                    modifiedOutputCount: snapshot.ModifiedResourceOutputCount),
                Workflow(
                    "export-resource-output",
                    "resources",
                    "Export Resource Output",
                    "Stage an editable output copy for file, HSD root, or A2D entry resources.",
                    "export-resource",
                    "<source-folder> <resource-address>",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: false,
                    targetCount: exportableResourceCount,
                    outputCount: snapshot.ResourceOutputCount,
                    modifiedOutputCount: snapshot.ModifiedResourceOutputCount),
                Workflow(
                    "import-resource-output",
                    "resources",
                    "Import Resource Output",
                    "Import replacement bytes into output-side files or same-size A2D entries.",
                    "import-resource",
                    "<source-folder> <resource-address> <input-file>",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: false,
                    requiresInputFile: true,
                    targetCount: importResourceCount,
                    outputCount: snapshot.ResourceOutputCount,
                    modifiedOutputCount: snapshot.ModifiedResourceOutputCount),
                Workflow(
                    "dump-resource-bytes",
                    "resources",
                    "Dump Resource Bytes",
                    "Write active resource bytes under resource-bytes/ in the output folder.",
                    "dump-resource-bytes",
                    "<source-folder> [resource-address]",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: true,
                    targetCount: readableResourceCount,
                    outputCount: snapshot.ResourceByteOutputCount,
                    modifiedOutputCount: snapshot.ModifiedResourceByteOutputCount),

                Workflow(
                    "list-maps",
                    "maps",
                    "List Maps",
                    "List map data/model/event-script bundles.",
                    "maps",
                    "<source-folder>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: snapshot.MapContextCount,
                    outputCount: snapshot.CompleteMapOutputCount,
                    modifiedOutputCount: snapshot.MapContexts.Sum(context => context.ModifiedOutputFileCount),
                    inspectionIssueCount: snapshot.MapInspectionErrorCount),
                Workflow(
                    "map-context",
                    "maps",
                    "Map Context",
                    "Inspect a map bundle with archive, resource, script, relationship, and output state.",
                    "map-context",
                    "<source-folder> [map-name-or-file]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: false,
                    targetCount: snapshot.MapContextCount,
                    outputCount: snapshot.MapContexts.Sum(context => context.OutputFileCount),
                    modifiedOutputCount: snapshot.MapContexts.Sum(context => context.ModifiedOutputFileCount),
                    inspectionIssueCount: snapshot.MapInspectionErrorCount),
                Workflow(
                    "copy-map-output",
                    "maps",
                    "Copy Map To Output",
                    "Stage all files belonging to a map bundle under the output folder.",
                    "copy-map",
                    "<source-folder> <map-name-or-file>",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: false,
                    targetCount: snapshot.MapCount,
                    outputCount: snapshot.MapContexts.Sum(context => context.OutputFileCount),
                    modifiedOutputCount: snapshot.MapContexts.Sum(context => context.ModifiedOutputFileCount)),

                Workflow(
                    "list-vehicles",
                    "vehicles",
                    "List Vehicles",
                    "List vehicle data bundles with shared common and kind-table archives.",
                    "vehicles",
                    "<source-folder> [vehicle-name-or-file]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: snapshot.VehicleContextCount,
                    outputCount: snapshot.VehicleContexts.Sum(context => context.OutputFileCount),
                    modifiedOutputCount: snapshot.VehicleContexts.Sum(context => context.ModifiedOutputFileCount),
                    inspectionIssueCount: snapshot.VehicleInspectionErrorCount),
                Workflow(
                    "vehicle-context",
                    "vehicles",
                    "Vehicle Context",
                    "Inspect a vehicle bundle with archive, resource, root, and output state.",
                    "vehicle-context",
                    "<source-folder> <vehicle-name-or-file>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: false,
                    targetCount: snapshot.VehicleContextCount,
                    outputCount: snapshot.VehicleContexts.Sum(context => context.OutputFileCount),
                    modifiedOutputCount: snapshot.VehicleContexts.Sum(context => context.ModifiedOutputFileCount),
                    inspectionIssueCount: snapshot.VehicleInspectionErrorCount),

                Workflow(
                    "list-a2d-packages",
                    "a2d-packages",
                    "List A2D Packages",
                    "List A2D package contexts, entries, sidecars, and packaged script tables.",
                    "a2d-packages",
                    "<source-folder> [package-relative-path]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: snapshot.A2DPackageContextCount,
                    outputCount: snapshot.A2DPackageContexts.Count(context => context.HasOutput) + snapshot.A2DEntryOutputCount,
                    modifiedOutputCount: snapshot.A2DPackageContexts.Count(context => context.HasModifiedOutput) + snapshot.ModifiedA2DEntryOutputCount,
                    inspectionIssueCount: snapshot.A2DPackageOpenErrorCount),
                Workflow(
                    "list-a2d-entries",
                    "a2d-packages",
                    "List A2D Entries",
                    "List package entries with offsets, sizes, script roles, and sidecar paths.",
                    "a2d-entries",
                    "<source-folder> [package-relative-path] [entry-name]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: a2dEntryCount,
                    outputCount: snapshot.A2DEntryOutputCount,
                    modifiedOutputCount: snapshot.ModifiedA2DEntryOutputCount),
                Workflow(
                    "extract-a2d-entry",
                    "a2d-packages",
                    "Extract A2D Entry",
                    "Extract an A2D package entry to an output-side sidecar file.",
                    "extract-a2d-entry",
                    "<source-folder> <package#entry>",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: false,
                    targetCount: a2dEntryCount,
                    outputCount: snapshot.A2DEntryOutputCount,
                    modifiedOutputCount: snapshot.ModifiedA2DEntryOutputCount),
                Workflow(
                    "replace-a2d-entry",
                    "a2d-packages",
                    "Replace A2D Entry",
                    "Replace a package entry from a same-size file into an output-side package copy.",
                    "replace-a2d-entry",
                    "<source-folder> <package#entry> <same-size-replacement-file>",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: false,
                    requiresInputFile: true,
                    targetCount: a2dEntryCount,
                    outputCount: snapshot.A2DPackageContexts.Count(context => context.HasOutput),
                    modifiedOutputCount: snapshot.A2DPackageContexts.Count(context => context.HasModifiedOutput)),
                Workflow(
                    "apply-a2d-entry-outputs",
                    "a2d-packages",
                    "Apply A2D Entry Outputs",
                    "Pack modified output-side A2D entry sidecars into output package copies.",
                    "apply-a2d-entry-outputs",
                    "<source-folder> [package-relative-path] [entry-name]",
                    isReadOnly: false,
                    writesOutput: true,
                    supportsBatch: true,
                    targetCount: snapshot.ModifiedA2DEntryOutputCount,
                    outputCount: snapshot.A2DEntryOutputCount,
                    modifiedOutputCount: snapshot.ModifiedA2DEntryOutputCount),

                Workflow(
                    "list-script-tables",
                    "script-tables",
                    "List Script Tables",
                    "List loose and packaged .tm script tables as toolkit resources.",
                    "script-tables",
                    "<source-folder> [resource-address|package-relative-path]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: snapshot.ScriptTableContextCount,
                    outputCount: snapshot.ScriptTableOutputCount,
                    modifiedOutputCount: snapshot.ModifiedScriptTableOutputCount),
                Workflow(
                    "script-contexts",
                    "script-tables",
                    "Script Contexts",
                    "Inspect loose or packaged script tables with output status and graph relationships.",
                    "script-contexts",
                    "<source-folder> [resource-address|package-relative-path]",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: true,
                    targetCount: snapshot.ScriptTableContextCount,
                    outputCount: snapshot.ScriptTableOutputCount,
                    modifiedOutputCount: snapshot.ModifiedScriptTableOutputCount),

                Workflow(
                    "mod-workspace",
                    "mod-output",
                    "Mod Workspace",
                    "Summarize staged project files, resource outputs, byte dumps, A2D sidecars, and map output completeness.",
                    "mod-workspace",
                    "<source-folder>",
                    isReadOnly: true,
                    writesOutput: false,
                    supportsBatch: false,
                    targetCount: snapshot.OutputFileCount + snapshot.ResourceByteOutputCount + snapshot.A2DEntryOutputCount,
                    outputCount: snapshot.OutputFileCount + snapshot.ResourceByteOutputCount + snapshot.A2DEntryOutputCount,
                    modifiedOutputCount: snapshot.ModifiedProjectOutputFileCount + snapshot.ModifiedResourceByteOutputCount + snapshot.ModifiedA2DEntryOutputCount),
            };

            return workflows.AsReadOnly();
        }

        private static KarProjectToolkitWorkflow Workflow(
            string id,
            string domainId,
            string displayName,
            string description,
            string command,
            string argumentHint,
            bool isReadOnly,
            bool writesOutput,
            bool supportsBatch,
            bool requiresInputFile = false,
            bool requiresValue = false,
            int targetCount = 0,
            int outputCount = 0,
            int modifiedOutputCount = 0,
            int inspectionIssueCount = 0)
        {
            return new KarProjectToolkitWorkflow(
                id,
                domainId,
                displayName,
                description,
                command,
                argumentHint,
                isReadOnly,
                writesOutput,
                supportsBatch,
                requiresInputFile,
                requiresValue,
                targetCount,
                outputCount,
                modifiedOutputCount,
                inspectionIssueCount);
        }
    }
}
