using System.Collections.Generic;
using static KARToolkit.Core.KarDataDefinitionFactory;

namespace KARToolkit.Core
{
    internal static class KarVehicleDataDefinitions
    {
        public static IReadOnlyList<KarDataDefinition> All { get; } = new[]
        {
            DefineSized(
                "kar.vc.common",
                "Vehicle Common Data",
                "Vehicles",
                "KAR_vcDataCommon",
                0x44,
                "Shared City Trial vehicle tables, common parameters, resource references, sound tables, and spawn data.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("commonParameterTable", 0x00, "KAR_vcCommonWordArray", "Shared vehicle parameter words.", true, "kar.vc.common.word"),
                Field("resourceTable", 0x04, "HSDArrayAccessor<KAR_vcCommonResourceEntry>", "Shared vehicle resource table.", true, "kar.vc.common.resourceEntry"),
                Field("physicsParameterTable", 0x08, "KAR_vcCommonWordArray", "Shared physics parameter words.", true, "kar.vc.common.word"),
                Field("machineClassSfxParams", 0x0C, "HSDArrayAccessor<KAR_vcCommonMachineClassSfxParam>", "Machine-class sound effect parameters.", true, "kar.vc.common.machineClassSfxParam"),
                Field("vehicleSoundTable", 0x10, "HSDFixedLengthPointerArrayAccessor<HSDArrayAccessor<KAR_vcCommonSoundEntry>>", "Per-machine sound id tables.", true),
                Field("x14", 0x14, "HSDFixedLengthPointerArrayAccessor<HSDAccessor>", "Unknown shared pointer table.", true),
                Field("x18", 0x18, "HSDAccessor", "Unknown shared data block.", true),
                Field("x1C", 0x1C, "KAR_vcCommonWordArray", "Unknown shared parameter words.", true, "kar.vc.common.word"),
                Field("spawnData", 0x20, "KAR_vcCommonSpawnData", "City Trial machine spawn setup.", true, "kar.vc.common.spawnData"),
                Field("x24", 0x24, "KAR_vcCommonWordArray", "Unknown shared parameter words.", true, "kar.vc.common.word"),
                Field("x28", 0x28, "KAR_vcCommonWordArray", "Unknown shared parameter words.", true, "kar.vc.common.word"),
                Field("x2C", 0x2C, "KAR_vcCommonWordArray", "Unknown shared parameter words.", true, "kar.vc.common.word")),
            DefineSized(
                "kar.vc.common.spawnData",
                "Vehicle Spawn Data",
                "Vehicles",
                "KAR_vcCommonSpawnData",
                0x14,
                "City Trial machine spawn timing, chance, weighted kind, and maximum spawn tables.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("spawnParamTableA", 0x00, "KAR_vcCommonWordArray", "Spawn parameter table A.", true, "kar.vc.common.word"),
                Field("spawnParamTableB", 0x04, "KAR_vcCommonWordArray", "Spawn parameter table B.", true, "kar.vc.common.word"),
                Field("spawnDesc", 0x08, "HSDArrayAccessor<KAR_vcCommonSpawnDesc>", "Progress-based machine spawn chances.", true, "kar.vc.common.spawnDesc"),
                Field("weightedSpawnKindTable", 0x0C, "HSDArrayAccessor<KAR_vcCommonWeightedSpawnKind>", "Weighted machine kind entries.", true, "kar.vc.common.weightedSpawnKind"),
                Field("maxSpawnWeights", 0x10, "HSDArrayAccessor<KAR_vcCommonMaxSpawnWeights>", "Maximum additional-machine spawn weights.", true, "kar.vc.common.maxSpawnWeights")),
            DefineSized(
                "kar.vc.common.word",
                "Vehicle Common Word",
                "Vehicles",
                "KAR_vcCommonWord",
                0x04,
                "Shared 32-bit value that can be read as a float, signed integer, or unsigned integer.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("floatValue", 0x00, "f32", "Value interpreted as a 32-bit float."),
                Field("intValue", 0x00, "s32", "Value interpreted as a signed 32-bit integer."),
                Field("uintValue", 0x00, "u32", "Value interpreted as an unsigned 32-bit integer.")),
            DefineSized(
                "kar.vc.common.resourceEntry",
                "Vehicle Common Resource Entry",
                "Vehicles",
                "KAR_vcCommonResourceEntry",
                0x08,
                "Shared vehicle resource pointer entry.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("data", 0x00, "HSDAccessor", "Resource data pointer.", true),
                Field("x04", 0x04, "u8", "Unknown byte."),
                Field("x05", 0x05, "u8", "Unknown byte."),
                Field("x06", 0x06, "u8", "Unknown byte."),
                Field("x07", 0x07, "u8", "Unknown byte.")),
            DefineSized(
                "kar.vc.common.machineClassSfxParam",
                "Machine Class SFX Parameter",
                "Vehicles",
                "KAR_vcCommonMachineClassSfxParam",
                0x1C,
                "Per-machine-class sound effect parameter row.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("x00", 0x00, "s32", "Unknown integer."),
                Field("volumeScale", 0x04, "f32", "Volume scale."),
                Field("x08", 0x08, "f32", "Unknown float."),
                Field("x0C", 0x0C, "f32", "Unknown float."),
                Field("x10", 0x10, "f32", "Unknown float."),
                Field("x14", 0x14, "f32", "Unknown float."),
                Field("x18", 0x18, "f32", "Unknown float.")),
            DefineSized(
                "kar.vc.common.spawnDesc",
                "Vehicle Spawn Chance Entry",
                "Vehicles",
                "KAR_vcCommonSpawnDesc",
                0x6C,
                "Progress-based chance row for each vehicle kind.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("matchProgress", 0x00, "f32", "City Trial match progress threshold."),
                Field("warpChance", 0x04, "f32", "Warp Star chance."),
                Field("compactChance", 0x08, "f32", "Compact Star chance."),
                Field("wingedChance", 0x0C, "f32", "Winged Star chance."),
                Field("shadowChance", 0x10, "f32", "Shadow Star chance."),
                Field("hydraChance", 0x14, "f32", "Hydra chance."),
                Field("bulkChance", 0x18, "f32", "Bulk Star chance."),
                Field("slickChance", 0x1C, "f32", "Slick Star chance."),
                Field("formulaChance", 0x20, "f32", "Formula Star chance."),
                Field("dragoonChance", 0x24, "f32", "Dragoon chance."),
                Field("wagonChance", 0x28, "f32", "Wagon Star chance."),
                Field("rocketChance", 0x2C, "f32", "Rocket Star chance."),
                Field("swerveChance", 0x30, "f32", "Swerve Star chance."),
                Field("turboChance", 0x34, "f32", "Turbo Star chance."),
                Field("jetChance", 0x38, "f32", "Jet Star chance."),
                Field("flightChance", 0x3C, "f32", "Flight Warp Star chance."),
                Field("freeChance", 0x40, "f32", "Free Star chance."),
                Field("steerChance", 0x44, "f32", "Steer Star chance."),
                Field("wingKirbyChance", 0x48, "f32", "Wing Kirby chance."),
                Field("wingMetaKnightChance", 0x4C, "f32", "Wing Meta Knight chance."),
                Field("wheelNormalChance", 0x50, "f32", "Wheel chance."),
                Field("wheelKirbyChance", 0x54, "f32", "Wheel Kirby chance."),
                Field("wheelieBikeChance", 0x58, "f32", "Wheelie Bike chance."),
                Field("rexWheelieChance", 0x5C, "f32", "Rex Wheelie chance."),
                Field("wheelieScooterChance", 0x60, "f32", "Wheelie Scooter chance."),
                Field("wheelDededeChance", 0x64, "f32", "Wheel Dedede chance."),
                Field("wheelVsDededeChance", 0x68, "f32", "Wheel Vs. Dedede chance.")),
            DefineSized(
                "kar.vc.common.weightedSpawnKind",
                "Weighted Spawn Kind Entry",
                "Vehicles",
                "KAR_vcCommonWeightedSpawnKind",
                0x08,
                "Weighted spawn kind row.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("kind", 0x00, "s32", "Spawn kind."),
                Field("weight", 0x04, "s32", "Spawn weight.")),
            DefineSized(
                "kar.vc.common.maxSpawnWeights",
                "Maximum Spawn Weights Entry",
                "Vehicles",
                "KAR_vcCommonMaxSpawnWeights",
                0x94,
                "Maximum additional-machine spawn weights and ordered spawn kind ids.",
                "HSDRaw/AirRide/Vc/KAR_vcDataCommon.cs",
                Field("oneAdditionalMachineWeight", 0x00, "f32", "Weight for one additional machine."),
                Field("twoAdditionalMachinesWeight", 0x04, "f32", "Weight for two additional machines."),
                Field("threeAdditionalMachinesWeight", 0x08, "f32", "Weight for three additional machines."),
                Field("fourAdditionalMachinesWeight", 0x0C, "f32", "Weight for four additional machines."),
                Field("fiveAdditionalMachinesWeight", 0x10, "f32", "Weight for five additional machines."),
                Field("sixAdditionalMachinesWeight", 0x14, "f32", "Weight for six additional machines."),
                Field("sevenAdditionalMachinesWeight", 0x18, "f32", "Weight for seven additional machines."),
                Field("eightAdditionalMachinesWeight", 0x1C, "f32", "Weight for eight additional machines."),
                Field("nineAdditionalMachinesWeight", 0x20, "f32", "Weight for nine additional machines."),
                Field("tenAdditionalMachinesWeight", 0x24, "f32", "Weight for ten additional machines."),
                Field("elevenAdditionalMachinesWeight", 0x28, "f32", "Weight for eleven additional machines."),
                Field("spawnKind00", 0x2C, "s32", "Spawn kind id 00."),
                Field("spawnKind01", 0x30, "s32", "Spawn kind id 01."),
                Field("spawnKind02", 0x34, "s32", "Spawn kind id 02."),
                Field("spawnKind03", 0x38, "s32", "Spawn kind id 03."),
                Field("spawnKind04", 0x3C, "s32", "Spawn kind id 04."),
                Field("spawnKind05", 0x40, "s32", "Spawn kind id 05."),
                Field("spawnKind06", 0x44, "s32", "Spawn kind id 06."),
                Field("spawnKind07", 0x48, "s32", "Spawn kind id 07."),
                Field("spawnKind08", 0x4C, "s32", "Spawn kind id 08."),
                Field("spawnKind09", 0x50, "s32", "Spawn kind id 09."),
                Field("spawnKind10", 0x54, "s32", "Spawn kind id 10."),
                Field("spawnKind11", 0x58, "s32", "Spawn kind id 11."),
                Field("spawnKind12", 0x5C, "s32", "Spawn kind id 12."),
                Field("spawnKind13", 0x60, "s32", "Spawn kind id 13."),
                Field("spawnKind14", 0x64, "s32", "Spawn kind id 14."),
                Field("spawnKind15", 0x68, "s32", "Spawn kind id 15."),
                Field("spawnKind16", 0x6C, "s32", "Spawn kind id 16."),
                Field("spawnKind17", 0x70, "s32", "Spawn kind id 17."),
                Field("spawnKind18", 0x74, "s32", "Spawn kind id 18."),
                Field("spawnKind19", 0x78, "s32", "Spawn kind id 19."),
                Field("spawnKind20", 0x7C, "s32", "Spawn kind id 20."),
                Field("spawnKind21", 0x80, "s32", "Spawn kind id 21."),
                Field("spawnKind22", 0x84, "s32", "Spawn kind id 22."),
                Field("spawnKind23", 0x88, "s32", "Spawn kind id 23."),
                Field("spawnKind24", 0x8C, "s32", "Spawn kind id 24."),
                Field("spawnKind25", 0x90, "s32", "Spawn kind id 25.")),
        };
    }
}
